<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="13" ignored="0" total="17" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Surefire suite" duration-ms="9112" started-at="2018-08-17T23:59:46Z" finished-at="2018-08-17T23:59:55Z">
    <groups>
      <group name="getcustomer">
        <method signature="CustomerOnboarding_GetCall.deleteCall_methodNotAllowed()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="deleteCall_methodNotAllowed" class="com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall"/>
        <method signature="CustomerOnboarding_GetCall.getCallWithContentTypeAsAny()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="getCallWithContentTypeAsAny" class="com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall"/>
        <method signature="CustomerOnboarding_GetCall.getCallWithContentTypeAsBinary()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="getCallWithContentTypeAsBinary" class="com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall"/>
        <method signature="CustomerOnboarding_GetCall.getCallWithContentTypeAsHtml()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="getCallWithContentTypeAsHtml" class="com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall"/>
        <method signature="CustomerOnboarding_GetCall.getCallWithContentTypeAsText()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="getCallWithContentTypeAsText" class="com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall"/>
        <method signature="CustomerOnboarding_GetCall.getCallWithContentTypeAsXml()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="getCallWithContentTypeAsXml" class="com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall"/>
        <method signature="CustomerOnboarding_GetCall.postCall_methodNotAllowed()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="postCall_methodNotAllowed" class="com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall"/>
        <method signature="CustomerOnboarding_GetCall.putCall_methodNotAllowed()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="putCall_methodNotAllowed" class="com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall"/>
        <method signature="CustomerOnboarding_GetCall.successGetCall()[pri:0, instance:com.project.api.testscenarios.functionalvalidationtests.CustomerOnboarding_GetCall@de648]" name="successGetCall" class="com.project.api.testscenarios.functionalvalidationtests.CustomerOnboarding_GetCall"/>
        <method signature="CustomerOnboarding_GetCall.successGetCall()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="successGetCall" class="com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall"/>
        <method signature="CustomerOnboarding_GetCall.successGetCall()[pri:0, instance:com.project.api.testscenarios.responsevalidationtests.CustomerOnboarding_GetCall@15670a]" name="successGetCall" class="com.project.api.testscenarios.responsevalidationtests.CustomerOnboarding_GetCall"/>
        <method signature="CustomerOnboarding_GetCall.testGetCallForInvalidCustomerId()[pri:0, instance:com.project.api.testscenarios.functionalvalidationtests.CustomerOnboarding_GetCall@de648]" name="testGetCallForInvalidCustomerId" class="com.project.api.testscenarios.functionalvalidationtests.CustomerOnboarding_GetCall"/>
        <method signature="CustomerOnboarding_GetCall.testGetCallForInvalidCustomerId()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="testGetCallForInvalidCustomerId" class="com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall"/>
        <method signature="CustomerOnboarding_GetCall.testGetCallWithInvalidPathParamType()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="testGetCallWithInvalidPathParamType" class="com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall"/>
        <method signature="CustomerOnboarding_GetCall.testGetCallWithInvalidSamlHeader()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="testGetCallWithInvalidSamlHeader" class="com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall"/>
        <method signature="CustomerOnboarding_GetCall.testGetCallWithInvalidUrl()[pri:0, instance:com.project.api.testscenarios.functionalvalidationtests.CustomerOnboarding_GetCall@de648]" name="testGetCallWithInvalidUrl" class="com.project.api.testscenarios.functionalvalidationtests.CustomerOnboarding_GetCall"/>
        <method signature="CustomerOnboarding_GetCall.testGetCallWithInvalidUrl()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="testGetCallWithInvalidUrl" class="com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall"/>
      </group> <!-- getcustomer -->
    </groups>
    <test name="Surefire test" duration-ms="9112" started-at="2018-08-17T23:59:46Z" finished-at="2018-08-17T23:59:55Z">
      <class name="com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall">
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="setUp" is-config="true" duration-ms="6" started-at="2018-08-17T23:59:49Z" finished-at="2018-08-17T23:59:49Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall.deleteCall_methodNotAllowed()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="deleteCall_methodNotAllowed()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="deleteCall_methodNotAllowed" duration-ms="414" started-at="2018-08-17T23:59:49Z" finished-at="2018-08-17T23:59:50Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[1 expectation failed.
Expected status code <405> doesn't match actual status code <404>.
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <405> doesn't match actual status code <404>.

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:451)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:613)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:120)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:128)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:117)
at com.project.app.api_test_v1.utilities.RestCalls.assertResponseCode(RestCalls.java:279)
at com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall.deleteCall_methodNotAllowed(CustomerOnboarding_GetCall.java:91)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:147)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteCall_methodNotAllowed -->
        <test-method status="PASS" signature="conclude(org.testng.ITestResult)[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="conclude" is-config="true" duration-ms="2" started-at="2018-08-17T23:59:50Z" finished-at="2018-08-17T23:59:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=deleteCall_methodNotAllowed status=FAILURE method=CustomerOnboarding_GetCall.deleteCall_methodNotAllowed()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- conclude -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="setUp" is-config="true" duration-ms="5" started-at="2018-08-17T23:59:50Z" finished-at="2018-08-17T23:59:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall.getCallWithContentTypeAsAny()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="getCallWithContentTypeAsAny()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="getCallWithContentTypeAsAny" duration-ms="409" started-at="2018-08-17T23:59:50Z" finished-at="2018-08-17T23:59:50Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[1 expectation failed.
Expected status code <406> doesn't match actual status code <404>.
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <406> doesn't match actual status code <404>.

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:451)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:613)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:120)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:128)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:117)
at com.project.app.api_test_v1.utilities.RestCalls.assertResponseCode(RestCalls.java:279)
at com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall.getCallWithContentTypeAsAny(CustomerOnboarding_GetCall.java:172)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:147)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getCallWithContentTypeAsAny -->
        <test-method status="PASS" signature="conclude(org.testng.ITestResult)[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="conclude" is-config="true" duration-ms="2" started-at="2018-08-17T23:59:50Z" finished-at="2018-08-17T23:59:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=getCallWithContentTypeAsAny status=FAILURE method=CustomerOnboarding_GetCall.getCallWithContentTypeAsAny()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- conclude -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="setUp" is-config="true" duration-ms="5" started-at="2018-08-17T23:59:50Z" finished-at="2018-08-17T23:59:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall.getCallWithContentTypeAsBinary()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="getCallWithContentTypeAsBinary()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="getCallWithContentTypeAsBinary" duration-ms="419" started-at="2018-08-17T23:59:50Z" finished-at="2018-08-17T23:59:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[1 expectation failed.
Expected status code <406> doesn't match actual status code <404>.
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <406> doesn't match actual status code <404>.

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:451)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:613)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:120)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:128)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:117)
at com.project.app.api_test_v1.utilities.RestCalls.assertResponseCode(RestCalls.java:279)
at com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall.getCallWithContentTypeAsBinary(CustomerOnboarding_GetCall.java:194)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:147)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getCallWithContentTypeAsBinary -->
        <test-method status="PASS" signature="conclude(org.testng.ITestResult)[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="conclude" is-config="true" duration-ms="1" started-at="2018-08-17T23:59:51Z" finished-at="2018-08-17T23:59:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=getCallWithContentTypeAsBinary status=FAILURE method=CustomerOnboarding_GetCall.getCallWithContentTypeAsBinary()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- conclude -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="setUp" is-config="true" duration-ms="3" started-at="2018-08-17T23:59:51Z" finished-at="2018-08-17T23:59:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall.getCallWithContentTypeAsHtml()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="getCallWithContentTypeAsHtml()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="getCallWithContentTypeAsHtml" duration-ms="408" started-at="2018-08-17T23:59:51Z" finished-at="2018-08-17T23:59:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[1 expectation failed.
Expected status code <406> doesn't match actual status code <404>.
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <406> doesn't match actual status code <404>.

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:451)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:613)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:120)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:128)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:117)
at com.project.app.api_test_v1.utilities.RestCalls.assertResponseCode(RestCalls.java:279)
at com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall.getCallWithContentTypeAsHtml(CustomerOnboarding_GetCall.java:183)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:147)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getCallWithContentTypeAsHtml -->
        <test-method status="PASS" signature="conclude(org.testng.ITestResult)[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="conclude" is-config="true" duration-ms="2" started-at="2018-08-17T23:59:51Z" finished-at="2018-08-17T23:59:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=getCallWithContentTypeAsHtml status=FAILURE method=CustomerOnboarding_GetCall.getCallWithContentTypeAsHtml()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- conclude -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="setUp" is-config="true" duration-ms="5" started-at="2018-08-17T23:59:51Z" finished-at="2018-08-17T23:59:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall.getCallWithContentTypeAsText()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="getCallWithContentTypeAsText()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="getCallWithContentTypeAsText" duration-ms="408" started-at="2018-08-17T23:59:51Z" finished-at="2018-08-17T23:59:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[1 expectation failed.
Expected status code <406> doesn't match actual status code <404>.
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <406> doesn't match actual status code <404>.

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:451)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:613)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:120)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:128)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:117)
at com.project.app.api_test_v1.utilities.RestCalls.assertResponseCode(RestCalls.java:279)
at com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall.getCallWithContentTypeAsText(CustomerOnboarding_GetCall.java:205)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:147)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getCallWithContentTypeAsText -->
        <test-method status="PASS" signature="conclude(org.testng.ITestResult)[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="conclude" is-config="true" duration-ms="1" started-at="2018-08-17T23:59:51Z" finished-at="2018-08-17T23:59:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=getCallWithContentTypeAsText status=FAILURE method=CustomerOnboarding_GetCall.getCallWithContentTypeAsText()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- conclude -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="setUp" is-config="true" duration-ms="4" started-at="2018-08-17T23:59:51Z" finished-at="2018-08-17T23:59:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall.getCallWithContentTypeAsXml()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="getCallWithContentTypeAsXml()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="getCallWithContentTypeAsXml" duration-ms="398" started-at="2018-08-17T23:59:51Z" finished-at="2018-08-17T23:59:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[1 expectation failed.
Expected status code <406> doesn't match actual status code <404>.
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <406> doesn't match actual status code <404>.

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:451)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:613)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:120)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:128)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:117)
at com.project.app.api_test_v1.utilities.RestCalls.assertResponseCode(RestCalls.java:279)
at com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall.getCallWithContentTypeAsXml(CustomerOnboarding_GetCall.java:216)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:147)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getCallWithContentTypeAsXml -->
        <test-method status="PASS" signature="conclude(org.testng.ITestResult)[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="conclude" is-config="true" duration-ms="2" started-at="2018-08-17T23:59:52Z" finished-at="2018-08-17T23:59:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=getCallWithContentTypeAsXml status=FAILURE method=CustomerOnboarding_GetCall.getCallWithContentTypeAsXml()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- conclude -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="setUp" is-config="true" duration-ms="5" started-at="2018-08-17T23:59:52Z" finished-at="2018-08-17T23:59:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall.postCall_methodNotAllowed()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="postCall_methodNotAllowed()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="postCall_methodNotAllowed" duration-ms="417" started-at="2018-08-17T23:59:52Z" finished-at="2018-08-17T23:59:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[1 expectation failed.
Expected status code <405> doesn't match actual status code <404>.
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <405> doesn't match actual status code <404>.

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:451)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:613)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:120)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:128)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:117)
at com.project.app.api_test_v1.utilities.RestCalls.assertResponseCode(RestCalls.java:279)
at com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall.postCall_methodNotAllowed(CustomerOnboarding_GetCall.java:81)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:147)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postCall_methodNotAllowed -->
        <test-method status="PASS" signature="conclude(org.testng.ITestResult)[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="conclude" is-config="true" duration-ms="2" started-at="2018-08-17T23:59:52Z" finished-at="2018-08-17T23:59:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=postCall_methodNotAllowed status=FAILURE method=CustomerOnboarding_GetCall.postCall_methodNotAllowed()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- conclude -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="setUp" is-config="true" duration-ms="6" started-at="2018-08-17T23:59:52Z" finished-at="2018-08-17T23:59:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall.putCall_methodNotAllowed()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="putCall_methodNotAllowed()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="putCall_methodNotAllowed" duration-ms="400" started-at="2018-08-17T23:59:52Z" finished-at="2018-08-17T23:59:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[1 expectation failed.
Expected status code <405> doesn't match actual status code <404>.
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <405> doesn't match actual status code <404>.

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:451)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:613)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:120)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:128)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:117)
at com.project.app.api_test_v1.utilities.RestCalls.assertResponseCode(RestCalls.java:279)
at com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall.putCall_methodNotAllowed(CustomerOnboarding_GetCall.java:101)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:147)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- putCall_methodNotAllowed -->
        <test-method status="PASS" signature="conclude(org.testng.ITestResult)[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="conclude" is-config="true" duration-ms="2" started-at="2018-08-17T23:59:53Z" finished-at="2018-08-17T23:59:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=putCall_methodNotAllowed status=FAILURE method=CustomerOnboarding_GetCall.putCall_methodNotAllowed()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- conclude -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="setUp" is-config="true" duration-ms="4" started-at="2018-08-17T23:59:53Z" finished-at="2018-08-17T23:59:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall.successGetCall()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="successGetCall()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="successGetCall" duration-ms="399" started-at="2018-08-17T23:59:53Z" finished-at="2018-08-17T23:59:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[1 expectation failed.
Expected status code <200> doesn't match actual status code <404>.
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <200> doesn't match actual status code <404>.

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:451)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:613)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:120)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:128)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:117)
at com.project.app.api_test_v1.utilities.RestCalls.assertResponseCode(RestCalls.java:279)
at com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall.successGetCall(CustomerOnboarding_GetCall.java:70)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:147)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- successGetCall -->
        <test-method status="PASS" signature="conclude(org.testng.ITestResult)[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="conclude" is-config="true" duration-ms="2" started-at="2018-08-17T23:59:53Z" finished-at="2018-08-17T23:59:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=successGetCall status=FAILURE method=CustomerOnboarding_GetCall.successGetCall()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- conclude -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="setUp" is-config="true" duration-ms="4" started-at="2018-08-17T23:59:53Z" finished-at="2018-08-17T23:59:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall.testGetCallForInvalidCustomerId()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testGetCallForInvalidCustomerId()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="testGetCallForInvalidCustomerId" duration-ms="398" started-at="2018-08-17T23:59:53Z" finished-at="2018-08-17T23:59:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetCallForInvalidCustomerId -->
        <test-method status="PASS" signature="conclude(org.testng.ITestResult)[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="conclude" is-config="true" duration-ms="1" started-at="2018-08-17T23:59:53Z" finished-at="2018-08-17T23:59:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testGetCallForInvalidCustomerId status=SUCCESS method=CustomerOnboarding_GetCall.testGetCallForInvalidCustomerId()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- conclude -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="setUp" is-config="true" duration-ms="3" started-at="2018-08-17T23:59:53Z" finished-at="2018-08-17T23:59:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall.testGetCallWithInvalidPathParamType()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testGetCallWithInvalidPathParamType()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="testGetCallWithInvalidPathParamType" duration-ms="396" started-at="2018-08-17T23:59:53Z" finished-at="2018-08-17T23:59:54Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[1 expectation failed.
Expected status code <403> doesn't match actual status code <404>.
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <403> doesn't match actual status code <404>.

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:451)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:613)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:120)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:128)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:117)
at com.project.app.api_test_v1.utilities.RestCalls.assertResponseCode(RestCalls.java:279)
at com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall.testGetCallWithInvalidPathParamType(CustomerOnboarding_GetCall.java:161)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:147)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetCallWithInvalidPathParamType -->
        <test-method status="PASS" signature="conclude(org.testng.ITestResult)[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="conclude" is-config="true" duration-ms="1" started-at="2018-08-17T23:59:54Z" finished-at="2018-08-17T23:59:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testGetCallWithInvalidPathParamType status=FAILURE method=CustomerOnboarding_GetCall.testGetCallWithInvalidPathParamType()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- conclude -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="setUp" is-config="true" duration-ms="3" started-at="2018-08-17T23:59:54Z" finished-at="2018-08-17T23:59:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall.testGetCallWithInvalidSamlHeader()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testGetCallWithInvalidSamlHeader()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="testGetCallWithInvalidSamlHeader" duration-ms="386" started-at="2018-08-17T23:59:54Z" finished-at="2018-08-17T23:59:54Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[1 expectation failed.
Expected status code <403> doesn't match actual status code <404>.
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <403> doesn't match actual status code <404>.

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:451)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:613)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:120)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:128)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:117)
at com.project.app.api_test_v1.utilities.RestCalls.assertResponseCode(RestCalls.java:279)
at com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall.testGetCallWithInvalidSamlHeader(CustomerOnboarding_GetCall.java:145)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:147)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetCallWithInvalidSamlHeader -->
        <test-method status="PASS" signature="conclude(org.testng.ITestResult)[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="conclude" is-config="true" duration-ms="2" started-at="2018-08-17T23:59:54Z" finished-at="2018-08-17T23:59:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testGetCallWithInvalidSamlHeader status=FAILURE method=CustomerOnboarding_GetCall.testGetCallWithInvalidSamlHeader()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- conclude -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="setUp" is-config="true" duration-ms="3" started-at="2018-08-17T23:59:54Z" finished-at="2018-08-17T23:59:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall.testGetCallWithInvalidUrl()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testGetCallWithInvalidUrl()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="testGetCallWithInvalidUrl" duration-ms="409" started-at="2018-08-17T23:59:54Z" finished-at="2018-08-17T23:59:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetCallWithInvalidUrl -->
        <test-method status="PASS" signature="conclude(org.testng.ITestResult)[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41]" name="conclude" is-config="true" duration-ms="1" started-at="2018-08-17T23:59:55Z" finished-at="2018-08-17T23:59:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testGetCallWithInvalidUrl status=SUCCESS method=CustomerOnboarding_GetCall.testGetCallWithInvalidUrl()[pri:0, instance:com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall@898b41] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- conclude -->
      </class> <!-- com.project.api.testscenarios.httpstatusvalidationtests.CustomerOnboarding_GetCall -->
      <class name="com.project.api.testscenarios.functionalvalidationtests.CustomerOnboarding_GetCall">
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.project.api.testscenarios.functionalvalidationtests.CustomerOnboarding_GetCall@de648]" name="setUp" is-config="true" duration-ms="29" started-at="2018-08-17T23:59:46Z" finished-at="2018-08-17T23:59:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.project.api.testscenarios.functionalvalidationtests.CustomerOnboarding_GetCall.successGetCall()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="successGetCall()[pri:0, instance:com.project.api.testscenarios.functionalvalidationtests.CustomerOnboarding_GetCall@de648]" name="successGetCall" duration-ms="2445" started-at="2018-08-17T23:59:46Z" finished-at="2018-08-17T23:59:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[1 expectation failed.
Expected status code <200> doesn't match actual status code <404>.
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <200> doesn't match actual status code <404>.

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:451)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:613)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:120)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:128)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:117)
at com.project.app.api_test_v1.utilities.RestCalls.assertResponseCode(RestCalls.java:279)
at com.project.api.testscenarios.functionalvalidationtests.CustomerOnboarding_GetCall.successGetCall(CustomerOnboarding_GetCall.java:69)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:147)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- successGetCall -->
        <test-method status="PASS" signature="conclude(org.testng.ITestResult)[pri:0, instance:com.project.api.testscenarios.functionalvalidationtests.CustomerOnboarding_GetCall@de648]" name="conclude" is-config="true" duration-ms="1" started-at="2018-08-17T23:59:48Z" finished-at="2018-08-17T23:59:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=successGetCall status=FAILURE method=CustomerOnboarding_GetCall.successGetCall()[pri:0, instance:com.project.api.testscenarios.functionalvalidationtests.CustomerOnboarding_GetCall@de648] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- conclude -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.project.api.testscenarios.functionalvalidationtests.CustomerOnboarding_GetCall@de648]" name="setUp" is-config="true" duration-ms="2" started-at="2018-08-17T23:59:48Z" finished-at="2018-08-17T23:59:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.project.api.testscenarios.functionalvalidationtests.CustomerOnboarding_GetCall.testGetCallForInvalidCustomerId()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testGetCallForInvalidCustomerId()[pri:0, instance:com.project.api.testscenarios.functionalvalidationtests.CustomerOnboarding_GetCall@de648]" name="testGetCallForInvalidCustomerId" duration-ms="398" started-at="2018-08-17T23:59:48Z" finished-at="2018-08-17T23:59:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetCallForInvalidCustomerId -->
        <test-method status="PASS" signature="conclude(org.testng.ITestResult)[pri:0, instance:com.project.api.testscenarios.functionalvalidationtests.CustomerOnboarding_GetCall@de648]" name="conclude" is-config="true" duration-ms="2" started-at="2018-08-17T23:59:49Z" finished-at="2018-08-17T23:59:49Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testGetCallForInvalidCustomerId status=SUCCESS method=CustomerOnboarding_GetCall.testGetCallForInvalidCustomerId()[pri:0, instance:com.project.api.testscenarios.functionalvalidationtests.CustomerOnboarding_GetCall@de648] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- conclude -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.project.api.testscenarios.functionalvalidationtests.CustomerOnboarding_GetCall@de648]" name="setUp" is-config="true" duration-ms="4" started-at="2018-08-17T23:59:49Z" finished-at="2018-08-17T23:59:49Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.project.api.testscenarios.functionalvalidationtests.CustomerOnboarding_GetCall.testGetCallWithInvalidUrl()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testGetCallWithInvalidUrl()[pri:0, instance:com.project.api.testscenarios.functionalvalidationtests.CustomerOnboarding_GetCall@de648]" name="testGetCallWithInvalidUrl" duration-ms="421" started-at="2018-08-17T23:59:49Z" finished-at="2018-08-17T23:59:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetCallWithInvalidUrl -->
        <test-method status="PASS" signature="conclude(org.testng.ITestResult)[pri:0, instance:com.project.api.testscenarios.functionalvalidationtests.CustomerOnboarding_GetCall@de648]" name="conclude" is-config="true" duration-ms="3" started-at="2018-08-17T23:59:49Z" finished-at="2018-08-17T23:59:49Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testGetCallWithInvalidUrl status=SUCCESS method=CustomerOnboarding_GetCall.testGetCallWithInvalidUrl()[pri:0, instance:com.project.api.testscenarios.functionalvalidationtests.CustomerOnboarding_GetCall@de648] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- conclude -->
      </class> <!-- com.project.api.testscenarios.functionalvalidationtests.CustomerOnboarding_GetCall -->
      <class name="com.project.api.testscenarios.responsevalidationtests.CustomerOnboarding_GetCall">
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.project.api.testscenarios.responsevalidationtests.CustomerOnboarding_GetCall@15670a]" name="setUp" is-config="true" duration-ms="3" started-at="2018-08-17T23:59:55Z" finished-at="2018-08-17T23:59:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.project.api.testscenarios.responsevalidationtests.CustomerOnboarding_GetCall.successGetCall()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="successGetCall()[pri:0, instance:com.project.api.testscenarios.responsevalidationtests.CustomerOnboarding_GetCall@15670a]" name="successGetCall" duration-ms="395" started-at="2018-08-17T23:59:55Z" finished-at="2018-08-17T23:59:55Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[1 expectation failed.
Expected status code <200> doesn't match actual status code <404>.
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <200> doesn't match actual status code <404>.

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:451)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:613)
at sun.reflect.GeneratedMethodAccessor151.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:120)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:128)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:117)
at com.project.app.api_test_v1.utilities.RestCalls.assertResponseCode(RestCalls.java:279)
at com.project.api.testscenarios.responsevalidationtests.CustomerOnboarding_GetCall.successGetCall(CustomerOnboarding_GetCall.java:68)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:147)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- successGetCall -->
        <test-method status="PASS" signature="conclude(org.testng.ITestResult)[pri:0, instance:com.project.api.testscenarios.responsevalidationtests.CustomerOnboarding_GetCall@15670a]" name="conclude" is-config="true" duration-ms="1" started-at="2018-08-17T23:59:55Z" finished-at="2018-08-17T23:59:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=successGetCall status=FAILURE method=CustomerOnboarding_GetCall.successGetCall()[pri:0, instance:com.project.api.testscenarios.responsevalidationtests.CustomerOnboarding_GetCall@15670a] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- conclude -->
      </class> <!-- com.project.api.testscenarios.responsevalidationtests.CustomerOnboarding_GetCall -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
